-- =====================================================
--  BOUNTY BOARD — DATABASE SCHEMA
--  Author: Endika Aryandhi
--  Description: Schema utama untuk tabel Buronan & Profil
-- =====================================================

-- ============================
-- 1. Tabel: fugitives (Buronan)
-- ============================
create table if not exists public.fugitives (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc', now()) not null,
  name text not null,
  alias text,
  description text,
  crime text,
  bounty_amount numeric,
  image_url text,
  last_seen text,
  status text default 'pending'  -- possible: 'wanted', 'captured', 'pending', 'rejected'
);

-- Index untuk pencarian nama
create index if not exists idx_fugitives_name
  on public.fugitives (name);

-- Index untuk penyortiran berdasarkan bounty
create index if not exists idx_fugitives_bounty
  on public.fugitives (bounty_amount);


-- =================================
-- 2. Tabel: profiles (User / Hunter)
-- =================================
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  avatar_url text,
  role text default 'hunter'    -- value: 'admin', 'hunter'
);

-- Index username
create index if not exists idx_profiles_username
  on public.profiles (username);


-- =================================
-- 3. Storage Bucket (Manual Step)
-- =================================
-- Di Supabase Dashboard:
-- Storage > Create Bucket:
--   Name: avatars
--   Public: Yes
-- Gunakan untuk menyimpan foto buronan & avatar user.

-- =================================
-- End of Schema
-- =================================
